### ISSUE TITLE
Merged RPC spans not correctly shown, multi value tags not shown

### ISSUE THREAD

**Issue by pavolloffay** [uber/jaeger-ui#55] opened 2017-08-15 13:20 UTC
Following screenshots shows:
* merged RPC spans are now shown (symbol `->`)
* multi value tags are not shown

![screenshot of jaeger ui 3](https://user-images.githubusercontent.com/5618424/29317554-bf276c8e-81cc-11e7-984b-2edcf8f07720.jpg)
![screenshot of jaeger ui 1](https://user-images.githubusercontent.com/5618424/29317540-a80d8d3a-81cc-11e7-9824-621a40a60b68.jpg)
![screenshot of jaeger ui 2](https://user-images.githubusercontent.com/5618424/29317539-a80adcde-81cc-11e7-9934-eac64221316a.jpg)

JSON: https://paste.fedoraproject.org/paste/1vNDb8L-OXZvZFeZVaBBUg
Jaeger `master/79fba12`
Discovered while testing https://github.com/uber/jaeger/pull/334

Reproducer:
https://github.com/pavolloffay/opentracing-java-examples/tree/jaeger-unknown-service-error-and-ui-issues
run spring-boot and curl localhost:8080/chaining

**Comment by tiffon** [comment] 2017-08-21 04:07
@pavolloffay Thanks for reporting this.

I tested things out with the JSON you linked. I was able to reproduce the behavior.

>- merged RPC spans are now shown (symbol `->`)

Not sure this is an error. The parent span does not have the `span.kind: client` tag, it has (multiple) `span.kind: server`.

@yurishkuro, can you weigh in?

>- multi value tags are not shown

This is a bug that should be resolved in PR #53.

**Comment by yurishkuro** [comment] 2017-08-21 14:25
in fact the very first span has `span.kind` tags with both `server` and `client` values. How did that happen? It looks like an instrumentation issue where the child span was not started for downstream call, so the parent server the span was tagged as a client.

**Closed** 2017-08-23 17:44 UTC
Labels: bug

**Comment by pavolloffay** [comment] 2017-08-28 07:59
> in fact the very first span has span.kind tags with both server and client values. How did that happen? It looks like an instrumentation issue where the child span was not started for downstream call, so the parent server the span was tagged as a client.

It's correct OT instrumentation with brave-ot. Maybe it's some brave magic... I wanted to check this again but the link to JSON is not valid anymore.
